### TAREFA 12 - METÓDOS NUMÉRICOS II

Membros:
* Isaac Miller
* Milton Cassul

Tarefa descrita no final das aula [Aula#20](https://drive.google.com/file/d/1yY4Es4gY5nBLG9JaUlwQywGrP58Oh0U0/view)

In [1]:
import numpy as np
import scipy.linalg as sci
np.set_printoptions(precision=5,suppress=True)

In [2]:
def potencia_inverso(A):
    v = np.ones((A.shape[0],1))
    tolerancia = 1E-10
    
    LU,piv = sci.lu_factor(A)         #LU tem o U na parte superior e o L na inferior
    
    lambda_ = 0
    dif = 1

    while dif > tolerancia:
        lambda_velho=lambda_
        x1 = v / np.linalg.norm(v)
        v = sci.lu_solve((LU, piv), x1)
        lambda_ = x1.T.dot(v)
        dif = abs((lambda_-lambda_velho)/lambda_)

        #print('autovetor = \n ',x1)
        #print('autovalor = ',lambda_,'\n')
        
    lambda_ = 1/lambda_
    return x1,lambda_

In [3]:
def potencia_deslocamento(A,desloc):
    A = A - (desloc*np.eye(A.shape[0]))

    vetor,valor = potencia_inverso(A)
    valor += desloc
    
    return vetor,valor

In [4]:
def eigen(A):
    desloc = np.linspace(4,50,5)       #Deslocamentos pra matriz A da tarefa
    autovetores,autovalores = [],[]
    
    for p in desloc:
        #print('\nDeslocamento = ',p)
        vetor,valor=potencia_deslocamento(A,p)
        autovetores.append(vetor)
        autovalores.append(valor)
        #print('autovetor = \n',vetor)
        #print('autovalor = ',valor)

    return autovetores,autovalores

In [5]:
def householder(A):
    n = A.shape[0]
    H = np.eye(n)
    A_ant = A
    
    for i in range(n-2):
        H_i = matriz_householder(A_ant, i)
        A = H_i.T.dot(A_ant).dot(H_i)
        A_ant = A
        H = H.dot(H_i)
        
    print('Matriz tridiagonal A_barra = \n',A,'\n')
    print("Matriz acumulada H de householder = \n",H,'\n')
    return A, H

In [6]:
def matriz_householder(A, i):
    n = A.shape[0]
    w,z = np.zeros(n),np.zeros(n)                  #w e w'
    
    
    w[i+1:n] = A[i+1:n,i]
    z[i+1] = np.linalg.norm(w) 
    N = w - z
    N /= np.linalg.norm(N)
    
    H = np.eye(n) - (2*np.outer(N,N))
    #print("Matriz de householder = ",H,'\n')
    return H

In [7]:
if __name__ == '__main__':
    A = np.array([[40, 8, 4, 2, 1], [8, 30, 12, 6, 2], [4, 12, 20, 1, 2], [2, 6, 1, 25, 4],[1, 2, 2, 4, 5]])
    n = A.shape[0]
    
    A_barra, H = householder(A)
    
    autovetores,autovalores = eigen(A_barra)
    autovetores = np.array([i.reshape(n) for i in autovetores])
    
    print('Autovetores e Autovalores de A_barra = \n')
    for i in range(n):
        print(autovetores[i],'---',autovalores[i])
    
    print('\n Autovetores e Autovalores de A = \n')
    autovetores_A = H.dot(autovetores.T)
    for i in range(n):
        print(autovetores_A[:,i],'---',autovalores[i])    

Matriz tridiagonal A_barra = 
 [[40.       9.21954  0.      -0.      -0.     ]
 [ 9.21954 39.82353  4.06759 -0.       0.     ]
 [ 0.       4.06759 15.06872  6.29137  0.     ]
 [-0.      -0.       6.29137 17.58996  5.86698]
 [-0.       0.       0.       5.86698  7.51779]] 

Matriz acumulada H de householder = 
 [[ 1.       0.       0.       0.       0.     ]
 [ 0.       0.86772 -0.44234  0.08856  0.2087 ]
 [ 0.       0.43386  0.55214 -0.60367 -0.37748]
 [ 0.       0.21693  0.70272  0.58707  0.33835]
 [ 0.       0.10847 -0.07529  0.53206 -0.83635]] 

Autovetores e Autovalores de A_barra = 

[ 0.0091  -0.0355   0.29192 -0.48995  0.82061] --- [[4.01488]]
[-0.04133  0.12711 -0.78698  0.34641  0.49274] --- [[11.64243]]
[ 0.10328 -0.18319  0.49439  0.79262  0.28829] --- [[23.64808]]
[ 0.70729 -0.66654 -0.20827 -0.10675 -0.02632] --- [[31.31147]]
[-0.69806 -0.71045 -0.08747 -0.01777 -0.00249] --- [[49.38315]]

 Autovetores e Autovalores de A = 

[ 0.0091  -0.03207  0.13179  0.18745 -0.97282] -